#!/usr/bin/env python3
"""Build production Stage JSON files and the browser registry from fixtures."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    'stage1': ROOT / 'docs/stage-editor/stage1.v1.draft.json',
    'stage2': ROOT / 'docs/stage-editor/stage2.v1.draft.json',
    'stage3': ROOT / 'docs/stage-editor/stage3.v1.draft.json',
    'stage4': ROOT / 'docs/stage-editor/stage4.v1.draft.json',
    'stage5': ROOT / 'docs/stage-editor/stage5.v1.draft.json',
    'stage6': ROOT / 'docs/stage-editor/stage6.v1.draft.json',
    'stage7': ROOT / 'docs/stage-editor/stage7.v1.draft.json',
}
TERRAIN_PROFILE_SOURCES = {
    'stage1-near-v1': ROOT / 'data/terrain-profiles/stage1-near-v1.json',
}
TYPE_PRIORITY = {'environment': 0, 'gimmick': 1, 'hazard': 2, 'wave': 3, 'terrain-object': 4, 'cue': 5, 'boss': 6}


def normalized(stage: dict) -> dict:
    result = json.loads(json.dumps(stage))
    result['items'] = sorted(result['items'], key=lambda item: (
        item['timing']['start'], TYPE_PRIORITY.get(item['type'], 99), item['id'],
    ))
    return result


def main() -> None:
    output_dir = ROOT / 'data/stages'
    output_dir.mkdir(parents=True, exist_ok=True)
    registry = {}
    for stage_id, source in SOURCES.items():
        stage = normalized(json.loads(source.read_text(encoding='utf-8')))
        output = output_dir / f'{stage_id}.v1.json'
        output.write_text(json.dumps(stage, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        registry[stage_id] = stage
    payload = json.dumps(registry, ensure_ascii=False, separators=(',', ':'))
    terrain_profiles = {
        profile_id: json.loads(source.read_text(encoding='utf-8'))
        for profile_id, source in TERRAIN_PROFILE_SOURCES.items()
    }
    terrain_payload = json.dumps(terrain_profiles, ensure_ascii=False, separators=(',', ':'))
    (ROOT / 'js/stages.generated.js').write_text(
        '// Generated by tools/build_stage_registry.py. Do not edit by hand.\n'
        f'globalThis.STAGE_DATA_REGISTRY = Object.freeze({payload});\n'
        f'globalThis.STAGE_TERRAIN_PROFILE_REGISTRY = Object.freeze({terrain_payload});\n',
        encoding='utf-8',
    )


if __name__ == '__main__':
    main()
