"""Compile data/barrage-patterns/*.json into a browser-loadable registry."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "data" / "barrage-patterns"
OUTPUT = ROOT / "js" / "barragePatterns.generated.js"


def load_patterns() -> dict[str, dict]:
    patterns: dict[str, dict] = {}
    SOURCE_DIR.mkdir(parents=True, exist_ok=True)
    for path in sorted(SOURCE_DIR.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        pattern_id = data.get("id")
        if not isinstance(pattern_id, str) or not pattern_id:
            raise ValueError(f"{path}: id가 없습니다")
        if pattern_id in patterns:
            raise ValueError(f"중복 패턴 id: {pattern_id}")
        patterns[pattern_id] = data
    return patterns


def build() -> Path:
    payload = json.dumps(load_patterns(), ensure_ascii=False, indent=2)
    OUTPUT.write_text(
        "// Generated by tools/build_barrage_patterns.py — 직접 수정하지 마세요.\n"
        f"globalThis.BARRAGE_PATTERN_DATA = Object.freeze({payload});\n",
        encoding="utf-8",
    )
    return OUTPUT


if __name__ == "__main__":
    print(build().relative_to(ROOT))
